AutomatedTellerMachine/Controllers/CheckingAccountController.cs
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    public class CheckingAccountController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CheckingAccount
        [Authorize]
        public ActionResult Index()
        {

            var userId = User.Identity.GetUserId();

            var checkingAccountId = db.CheckingAccoutnts.Where(a => a.ApplicationUserId == userId).First().Id;

            ViewBag.CheckingAccountId = checkingAccountId;


            return View();
        }

        // GET: CheckingAccount/Details/5
        public ActionResult Details()
        {
            var userId = User.Identity.GetUserId();
            var checkingAccount = db.CheckingAccoutnts.Where(a => a.ApplicationUserId == userId).First();
            //var checkingAccount = new CheckingAccount
            //{
            //    AccountNumber = "0000123456",
            //    FirstName = "Michael",
            //    LastName = "Scott",
            //    Balance = 500
            //};
            return View(checkingAccount);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DetailsForAdmin(int id)
        {
            var checkingAccount = db.CheckingAccoutnts.Find(id);
            return View("Details", checkingAccount);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult List()
        {
            return View(db.CheckingAccoutnts.ToList());
        }


        // GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AutomatedTellerMachine/Controllers/HomeController.cs
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    public class HomeController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]
        public ActionResult Index()
        {

            var userId = User.Identity.GetUserId();

            var checkingAccountId = db.CheckingAccoutnts.Where(a => a.ApplicationUserId == userId).First().Id;

            ViewBag.CheckingAccountId = checkingAccountId;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Having truble send s a message";

            return View();
        }

        [HttpPost]
        public ActionResult Contact(string message)
        {
            //Do 

            ViewBag.TheMessage = "Thanks, got it";

            return PartialView("_ContactThanks");
            //return View();
        }

        public ActionResult Foo()
        {
            return View("About");
        }

        public ActionResult Serial(string letterCase)
        {
            var serial = "ASPNETMVCATM1";
            if (letterCase == "lower")
            {
                return Content(serial.ToLower());
            }
            return Content(serial);
        }
    }
}

AutomatedTellerMachine/Controllers/TransactionController.cs
using AutomatedTellerMachine.Models;
using AutomatedTellerMachine.Services;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {

        private IApplicationDbContext db;

        public TransactionController()
        {
            db = new ApplicationDbContext();
        }
        public TransactionController(IApplicationDbContext dbContext)
        {
            db = dbContext;
        }

        public ActionResult Deposit(int CheckingAccountId)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Deposit(Transaction transaction)
        {

            if (ModelState.IsValid)
            {
                db.Transactions.Add(transaction);
                db.SaveChanges();

                var service = new CheckingAccountService(db);
                service.UpdateBalance(transaction.CheckingAccountId);

                return RedirectToAction("Index", "Home");

            }

            return View();
        }
    }
}

AutomatedTellerMachine/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AutomatedTellerMachine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>


<div id="formSection">
    <h3>@ViewBag.TheMessage</h3>
    <form method="post" id="contactForm">
        <textarea name="message"></textarea>
        <input type="submit" value="Send" />
    </form>
    <img src="~/Content/Images/omp.png" id="progress" style="display: none;"/>
</div>
@section scripts {
    <script>
        $('#contactForm').submit(function () {
            $('#progress').show();
            $.post('', { message: $('#message').val() }).done(function(response) {
                setTimeout(function() { $('#formSection').html(response); }, 2000);
            });
            return false;
        });
    </script>
}

@*<div id="formSection">
            <h3>@ViewBag.TheMessage</h3>

            @using (Ajax.BeginForm(new AjaxOptions {HttpMethod = "post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "formSection"}))
            {
                <textarea name="message"></textarea>
                <input type="submit" value="Send"/>

            }
        </div>
    @section scripts {

        <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    }*@

AutomatedTellerMachine/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-circle-arrow-down">
            </span> Withdrawl
        </a>

        <a href="" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-flash">
            </span> Quick Cash $100
        </a>

        <a href="@Url.Action("Details", "CheckingAccount")" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-question-sign">
            </span> Balance Inquiry
        </a>
    </div>
    <div class="col-md-6 margin-top-20">
        <a href="" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-print">
            </span> Print Statement
        </a>

        <a href="" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-transfer">
            </span> Transfer Funds
        </a>

        <a href="@Url.Action("Deposit", "Transaction", new {checkingAccountId = ViewBag.CheckingAccountId})" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-circle-arrow-up">
            </span> Deposit
        </a>
    </div>

</div>

You are using @Request.Browser.Browser, and that's OK!

@{
    var amounts = new List<decimal> {100, 25.50m, -40, 275.99m};

    
}

<ul>
    @foreach (decimal amount in amounts)
    {
        <li>
            @formatAmount(amount)
        </li>
    }
</ul>

@helper formatAmount(decimal amount)
{
    var color = "green";

    if (amount < 0)
    {
        color = "red";
    }

    <span style="color: @color">@string.Format("{0:c}", amount)</span>
}

AutomatedTellerMachine/Views/Home/_ContactThanks.cshtml
<h3>@ViewBag.TheMessage</h3>